### ISSUE TITLE
Ergonomis suggest

### ISSUE THREAD

**Issue by Ygarr** [rabauke/harbour-babbage#3]
Increase size of plus button.
Cnage color of equal button

**Comment by rabauke** [comment]
Intentionally the "=" button is larger than others, not the "+" button as it is in traditional simple hardware pocket calculators. This is because the simple pocket calculator mode works differently from real pocket calculators, which display an intermediate result after hitting an operation key. Babbage does not show intermediate results but shows end results via "=" and respects operator precedence and parentheses.
